ДЗ 1
grobert608/2020-2-Atom-QA-Python-R-Gaptrakhmanov pull request #1
Opened 2020-09-24 17:50 UTC by grobert608

# Домашнее задание №1

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* Написаны по 5 тестоа на различные структуры (List, Set, Dictionary, String, Int)
* Как минимум один тест на каждую структуру был параметризован.
* Как минимум один тест на каждую структуру находится в классе.

2020-09-24 19:23 UTC, SK1995 requested changes
В целом неплохо, но не нашел параметризованных тестов.
Просто добавление фикстуры к тестам не делает тест параметризованным, чтобы его параметризовать, нужно использовать [@pytest.mark.parametrize](https://docs.pytest.org/en/2.8.7/parametrize.html#pytest-mark-parametrize).

2020-09-24 19:23 UTC, SK1995 commented on hw1/code/tests/test_int.py
> +    with pytest.raises(ZeroDivisionError):
Здесь не надо использовать `assert`.
Тест проверяет, что при делении на 0 происходит исключение, но ничего ни с чем не сравнивает.

2020-09-24 19:23 UTC, SK1995 commented on hw1/code/tests/test_set.py
> +        assert set_update == set_result
А может просто сделать `assert set_first.update(set_second) == set_result`?
И читаемость не страдает, и лишних сущностей так мы не создаем.

2020-09-25 08:36 UTC, grobert608 commented
> В целом неплохо, но не нашел параметризованных тестов, оставил пару комментариев по коду.
> Просто добавление фикстуры к тесту не делает его параметризованным, чтобы его параметризовать, нужно использовать [@pytest.mark.parametrize](https://docs.pytest.org/en/2.8.7/parametrize.html#pytest-mark-parametrize).

Спасибо, все поправил и добавил параметризованные тесты (запутался в формулировках)

2020-09-26 22:33 UTC, SK1995 approved these changes

2020-09-26 22:35 UTC, SK1995 commented
Все отлично, поставил максимум (4 балла).
Но в следующий раз буду снимать, если какого-то пункта дз не будет в работе, сданной с 1й попытки :)

2020-09-26 22:35 UTC, merged