ДЗ 2
grobert608/2020-2-Atom-QA-Python-R-Gaptrakhmanov pull request #2
Opened 2020-10-11 13:08 UTC by grobert608

# Домашнее задание №2

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* По дефолту тесты запускаются локально в стоковом браузере через webdriver_manager 
* Если передан параметр --selenoid='<host:port>', то тесты идут на запущенный selenoid
* Весь код реализован на паттерне PageObject
* Позитивный и негативный тест на авторизацию
* Фикстура, которая будет авторизовываться и возвращать объект главной страницы 
* Тест на создание рекламной кампании любого типа и проверять что она создана
* Тест на создание сегмента в аудиториях и проверить что сегмент создан 
* Тест на удаление сегмента после создания

2020-10-16 00:40 UTC, snicks92 requested changes
Хорошая работа, несколько комментов ниже

2020-10-16 00:40 UTC, snicks92 commented on hw2/code/ui/locators/locators.py
> +        By.XPATH, '/html/body/div[1]/div/div[2]/div[2]/div/div/div[1]/div/div[1]/div[1]/div[1]/div/div')
очень страшный локатор

2020-10-16 00:40 UTC, snicks92 commented on hw2/code/ui/locators/locators.py
> +                  '/html/body/div[1]/div[2]/div[1]/div/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div[4]/div[2]/div/div[3]/div[1]/div/div[1]/div/div/input')
еще страшнее =)

2020-10-16 00:40 UTC, snicks92 commented on hw2/code/ui/pages/auth_page.py
> +            return InvalidAuthPage(self.driver, self.config)
кажется, проверять что логин не удался на каждый логин - это довольно дорого. лучше в конкретном тесте отдельно проверить что появилась страница неудачного входа

2020-10-16 00:40 UTC, snicks92 commented on hw2/code/tests/test_ui.py
> +        assert ++cnt_after == cnt_before
если я все верно понял то надо дождаться когда сегмент удалится и проверять что cnt_after == cnt_before - 1

2020-10-16 07:38 UTC, grobert608 commented on hw2/code/tests/test_ui.py
> +        assert ++cnt_after == cnt_before
Именно, вроде `++cnt_after == cnt_before` аналогично `cnt_after == cnt_before - 1` :)

2020-10-16 12:18 UTC, snicks92 commented on hw2/code/tests/test_ui.py
> +        assert ++cnt_after == cnt_before
Как видишь нет.

```python
before = 1
after = 0
assert ++before == after
Traceback (most recent call last):
  File "<input>", line 1, in <module>
AssertionError

assert ++before == after + 1

```

Собственно в твоих тестах то же самое, ты слишком быстр ищешь число сегментов после удаления, получаешь то же число что и в cnt_before и тест проходит.

2020-10-16 15:17 UTC, grobert608 commented on hw2/code/tests/test_ui.py
> +        assert ++cnt_after == cnt_before
Ого, справедливо! 
Спасибо большое, я что-то упустил этот момент)
Поправлю слипом на 3 секунды:)

2020-10-16 15:24 UTC, grobert608 commented on hw2/code/ui/locators/locators.py
> +                  '/html/body/div[1]/div[2]/div[1]/div/div[2]/div[2]/div[2]/div/div[1]/div[2]/div/div[4]/div[2]/div/div[3]/div[1]/div/div[1]/div/div/input')
Я потренировался на некоторых примерах, потом я пытался добиться работоспособности и из-за нехватки времени сделал такой некрасивый вариант. Все понимаю, но лучше начну делать 3 дз)

2020-10-16 15:28 UTC, grobert608 commented
Поправил замечания по тестам)

Спасибо!

2020-10-17 12:50 UTC, snicks92 commented
Теперь ок, за локаторы таки сниму 1 балл, думаю это справедливо

2020-10-17 12:50 UTC, snicks92 approved these changes

2020-10-17 12:50 UTC, merged