HW3
grobert608/2020-2-Atom-QA-Python-R-Gaptrakhmanov pull request #3
Opened 2020-10-18 11:48 UTC by grobert608

# Домашнее задание №3

Прошу @snicks92 или @z1ll1 или @SK1995 проверить его.

Что было сделано:
* Настроено окружение для запуска API тестов
* API тесты запускаются через марк -m API
* Написан клиент, который будет иметь возможность авторизовываться
* Написан тест на создание сегмента через API и проверку что сегмент создан
* Написан тест на удаление сегмента через API

2020-10-20 10:57 UTC, snicks92 requested changes
Все ок, давай добавим проверок

2020-10-20 10:57 UTC, snicks92 commented on hw3/code/tests/test_api.py
> +        assert api_client.create(segment).status_code == 200
статус код 200 это конечно хорошо, но это не гарант что сегмент действительно создан. надо проверить что он появился в списке сегментов

2020-10-20 10:57 UTC, snicks92 commented on hw3/code/tests/test_api.py
> +        assert api_client.delete(id) == 204
логично, что тут надо проверить что сегмента в списке сегментов нет

2020-10-20 16:42 UTC, grobert608 commented on hw3/code/tests/test_api.py
> +        assert api_client.create(segment).status_code == 200
Разве нельзя полагать, что если не код ошибки, а код 200, например, то все успешно создано? Зачем мне тогда эти коды и нужны? Это ведь индикация успешности обработки запроса?

2020-10-21 20:56 UTC, snicks92 commented on hw3/code/tests/test_api.py
> +        assert api_client.create(segment).status_code == 200
Ну представь ситуацию что АПИ сломано настолько что на любой запрос ответ 200. А на самом деле ничего не произошло. Коды нужны в проде для микросервисного взаимодействия. В тестировании надо убеждаться что действие действительно произошло, дополнительно к коду. Причем первое важнее.

2020-10-21 20:58 UTC, grobert608 commented on hw3/code/tests/test_api.py
> +        assert api_client.create(segment).status_code == 200
Спасибо большое, осознал, поправлю на неделе

2020-10-22 21:44 UTC, grobert608 commented
Спасибо, поправил замечания!

2020-10-23 13:01 UTC, snicks92 approved these changes

2020-10-23 13:01 UTC, snicks92 commented
Теперь хорошо, спасибо, принято

2020-10-23 13:01 UTC, merged